### ISSUE TITLE
Autoload.php

### ISSUE THREAD

**Issue by natefourteen** [superXdev/enam#1]
PHP Warning:  require(/root/Downloads/New/enam/vendor/autoload.php): failed to open stream: No such file or directory in /root/Downloads/New/enam/artisan on line 18                                                                            PHP Warning:  require(/root/Downloads/New/enam/vendor/autoload.php): failed to open stream: No such file or directory in /root/Downloads/New/enam/artisan on line 18                                                                            PHP Fatal error:  require(): Failed opening required '/root/Downloads/New/enam/vendor/autoload.php' (include_path='.:/usr/share/php') in /root/Downloads/New/enam/artisan on line 18

**Comment by superXdev** [comment]
Run `composer install`

**Comment by natefourteen** [comment]
Solved, the package requires php ^7.3.
Please add note for system requirements.
Thanks in advance

**Comment by superXdev** [comment]
Ok, thanks for your suggestion
